### ISSUE TITLE
Error building gvpp.cpp

### ISSUE THREAD

**Issue by matheusPereiraAlmeida** [neurovertex/gvpp#1]
Hi, 

I'mtrying to build this repo [approxProbTraceAlign](https://github.com/jackbergus/approxProbTraceAlign) and I'm using ubuntu-22.04 and I downloaded the graphviz dependencies as described in the repo. One of its dependencies is gvpp.cpp, but i'm getting the following error when I use the comando make -j8 fuzzyStringMatching2:

Consolidate compiler generated dependencies of target gvpp
[  0%] Building CXX object submodules/gvpp/CMakeFiles/gvpp.dir/src/gvpp.cpp.o
Consolidate compiler generated dependencies of target yaml-cpp
[ 14%] Built target yaml-cpp
Consolidate compiler generated dependencies of target antlr4_static
[ 71%] Built target antlr4_static
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp:95:21: error: template-id not allowed for destructor
   95 |     AbstractGraphI::~AbstractGraphI() {
      |                     ^
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp: In member function ‘gvpp::GvAttributes<chartype>& gvpp::AbstractGraph<chartype>::getAttrsT(gvpp::AttrType) [with chartype = char]’:
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp:172:5: warning: control reaches end of non-void function [-Wreturn-type]
  172 |     }
      |     ^
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp: In member function ‘const gvpp::GvAttributes<chartype>& gvpp::AbstractGraph<chartype>::getAttrsT(gvpp::AttrType) const [with chartype = char]’:
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp:160:5: warning: control reaches end of non-void function [-Wreturn-type]
  160 |     }
      |     ^
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp: In member function ‘gvpp::GvAttributes<chartype>& gvpp::AbstractGraph<chartype>::getAttrsT(gvpp::AttrType) [with chartype = wchar_t]’:
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp:172:5: warning: control reaches end of non-void function [-Wreturn-type]
  172 |     }
      |     ^
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp: In member function ‘const gvpp::GvAttributes<chartype>& gvpp::AbstractGraph<chartype>::getAttrsT(gvpp::AttrType) const [with chartype = wchar_t]’:
/home/matheus/Documents/approxProbTraceAlign/submodules/gvpp/src/gvpp.cpp:160:5: warning: control reaches end of non-void function [-Wreturn-type]
  160 |     }
      |     ^
make[3]: *** [submodules/gvpp/CMakeFiles/gvpp.dir/build.make:76: submodules/gvpp/CMakeFiles/gvpp.dir/src/gvpp.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:12214: submodules/gvpp/CMakeFiles/gvpp.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1279: CMakeFiles/fuzzyStringMatching2.dir/rule] Error 2
make: *** [Makefile:190: fuzzyStringMatching2] Error 2

Can you help me figure it out? Thanks!!

**Comment by compilin** [comment]
Hello.

Had to rummage around a bit but I found the issue : gcc 9 builds gvpp fine in both c++17 and 20, but gcc12 will error out on c++12 because of some non-standard syntax I used. The commit I just pushed should fix that (and the -Wreturn-type warnings)

Oh and a small tips for github issues if I may : if you have to include snippets of code or logs in an issue or in comments, [put them in backticks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) ! Makes it easier to read ^^

**Comment by matheusPereiraAlmeida** [comment]
It worked, thank you!!! 

And thanks for the tip =) I'll do it next time hehe
